language: java
sudo: false

notifications:
  email: false

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: "Build modules & pre-cache"
      script: skip
    - stage: test
      script: mvn exec:java
    - # stage name not required, will continue to use `test`
      script: mvn test
    - stage: sonar
      script: echo "$SONAR_LOGIN" | mvn sonar:sonar -Dsonar.login="$SONAR_LOGIN"
